
# mysql配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/imooc-demo?useUnicode=yes&characterEncoding=utf-8
#    username: root
#    password: root
#  session:
#    store-type: none


  session:
      store-type: none

#security:
#  basic:
#    enabled: false
server:
  port: 8090


imooc:
  security:
    browser:
#      loginPage: /demo-signIn.html
#      loginResponseType: REDIRECT
      loginResponseType: JSON
    code:
      image:
        width: 67
        height: 100
        url:
#        url: /user,/user/*