
# mysql配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/imooc-demo?useUnicode=yes&characterEncoding=utf-8
#    username: root
#    password: root
#  session:
#    store-type: none

spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@172.21.130.130:1533:labdwt01
      username: DW_ADMIN
      password: admin_dw123

  session:
      store-type: none

#security:
#  basic:
#    enabled: false
server:
  port: 8090


imooc:
  security:
    browser:
#      loginPage: /demo-signIn.html
#      loginResponseType: REDIRECT
      loginResponseType: JSON