
# mysql配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/imooc-demo?useUnicode=yes&characterEncoding=utf-8
#    username: root
#    password: root
#  session:
#    store-type: none


#security:
#  basic:
#    enabled: false
server:
  port: 8090
  #对tomcat进行了一个优化配置
  tomcat:
    min-spare-threads: 20
    max-threads: 100
    max-connections: 5000


imooc:
  security:
#    browser:
#      loginPage: /demo-signIn.html
#      loginResponseType: REDIRECT
    code:
      image:
        width: 67
        height: 100
        url:
#        url: /user,/user/*
      sms:
        length: 4
    social:
      qq:
        app-id: 101386962
        app-secret: 2a0f820407df400b84a854d054be8b6a
#logging:
#  level:
#    org.springframework.security: debug
